### ISSUE TITLE
Несоответствие стандартам написания графического интерфейса.

### ISSUE THREAD

**Issue by Riobener** [Dedicated407/IKBO-06-19#2]
Программа не про дружелюбный интерфейс (отступы вышли из чата). Yes or no? Скрытые и важные функции через Shift+ЛКМ? В целом, очень невероятные и сомнительные решения. 
![111](https://user-images.githubusercontent.com/33630357/133839875-c97f1b73-16b3-4ab3-aa0d-af15c18628bb.jpg)
![11](https://user-images.githubusercontent.com/33630357/133839878-9abcdd9b-89b7-474f-951d-80ac2221d7cc.jpg)
![1](https://user-images.githubusercontent.com/33630357/133839880-11455473-6353-4119-9ce9-b4908cd3a97c.jpg)

**Comment by MaxBQb** [comment]
Про выбор столика через список - спорно.
Cогласен по поводу отступов и выбор по yes/no
Про shift, опять же, спорно... мне так удобней, например :)

**Comment by Riobener** [comment]
3 скрин не про выбор столика через список(про такое решение я ничего не писал). Он про отсутствие отступов) Скрины не в том порядке загрузились
> Про выбор столика через список - спорно.
> Cогласен по поводу отступов и выбор по yes/no
> Про shift, опять же, спорно... мне так удобней, например :)

**Comment by MaxBQb** [comment]
Понял, ну про отступы я сказал, с этим согласен
