### ISSUE TITLE
Существует возможность закрыть счёт без согласия пользователя

### ISSUE THREAD

**Issue by elkincode** [Dedicated407/IKBO-06-19#3]
Согласно пункту 2 приложенной документации, программный продукт должен позволять закрывать счёт только с согласия пользователя. Если принудительно закрыть всплывающее окно с подтверждением заказа, то счет будет закрыт без подтверждения согласия со стороны пользователя.
![qD1zEMS8quA](https://user-images.githubusercontent.com/74602029/133840113-378bfba3-b48a-4260-a62c-ca46db43a82e.jpg)
![WKXzySgmbWg](https://user-images.githubusercontent.com/74602029/133840120-1757ed54-2d4f-487a-afb0-6be9c50c449f.jpg)

**Comment by MaxBQb** [comment]
Да, этот баг нами был предусмотрен.
