### ISSUE TITLE
Неверное описание продукта (Виски)

### ISSUE THREAD

**Issue by Riobener** [Dedicated407/IKBO-06-19#4]
С одной стороны, Виски - алкоголь, но содержит 0% алкоголя. С другой стороны, если не алкоголь, зачем он стоит среди алкогольных напитков.
![image](https://user-images.githubusercontent.com/33630357/133840221-815fefb2-2ce0-471b-91c4-54d58e3afd26.png)

**Comment by MaxBQb** [comment]
Это одна и та же ошибка, поэтому дважды не зачту..
