### ISSUE TITLE
Позволяет купить алкоголь при возрасте менее 18 лет. 

### ISSUE THREAD

**Issue by Riobener** [Dedicated407/IKBO-06-19#5]
Продолжая историю с виски, возможно что-то из этого ломается по этой причине #4
![Скриншот 17-09-2021 220429](https://user-images.githubusercontent.com/33630357/133840771-4d6e2f89-2f34-40f8-910f-0c7a4739ae4c.jpg)
![Скриншот 17-09-2021 220440](https://user-images.githubusercontent.com/33630357/133840772-50a4cc55-749a-45a6-b307-e3c5705d8294.jpg)
![Скриншот 17-09-2021 220444](https://user-images.githubusercontent.com/33630357/133840774-e4289351-3630-4ffa-9e37-1694e0d15453.jpg)

**Comment by MaxBQb** [comment]
Да, это намеренная ошибка, молодец!
