### ISSUE TITLE
Некорректное отображение конечной стоимости заказа

### ISSUE THREAD

**Issue by elkincode** [Dedicated407/IKBO-06-19#6]
Согласно пункту 10 приложенной документации, программный продукт должен корректно считать конечную стоимость заказа. Стоимость одной ватрушки составляет 44.9 рубля, общая стоимость заказа из двух ватрушек вместо 89,8 рублей составила 88 рублей.

![J0n2IJCMbs0](https://user-images.githubusercontent.com/74602029/133840757-6687ecbc-bc28-49c2-b804-38cd8660a838.jpg)

**Comment by tenor7** [comment]
Такая же ошибка происходит и с напитком "водка-медведь". Стоимость одного напитка составляет 999,99 , а стоимость из двух этих напитков составляет 1999, вместо 1999,98

**Comment by MaxBQb** [comment]
Браво! Это действительно есть в списке багов)
К слову.. при заказе через бронирование столика, такого бага вы не найдёте (разная реализация одного интерфейса)
