### ISSUE TITLE
Проблема с бронированием столиков

### ISSUE THREAD

**Issue by Riobener** [Dedicated407/IKBO-06-19#7]
Столик номер 6 уже давно не занят, но при выборе его нет. Достигается путем закрытия окна с занятым столиком, параллельно оставляя окно со следующим бронированием открытым. Выпадающее меню динамически не обновляется.
![5](https://user-images.githubusercontent.com/33630357/133841124-e60c34a2-a600-426b-a525-c1ff1f61856e.jpg)
![5 (2)](https://user-images.githubusercontent.com/33630357/133841125-a1d1abd8-83a5-4fca-af41-b110420a90f6.jpg)

**Comment by MaxBQb** [comment]
Выбор столика формируется на момент прихода клиента, нигде не указано, что он должен актуализироваться (там есть другие вещи, которые должны)
В любом случае это действительно не самое логичное поведение, можно и поправить
