### ISSUE TITLE
Некорректная валидация полей

### ISSUE THREAD

**Issue by BabichAndrey** [Dedicated407/IKBO-06-19#8]
![sdyflT1Px8U](https://user-images.githubusercontent.com/44177068/133840298-6f40bbb4-381d-4f96-90e4-ca8e54ea343a.jpg)
Существует возможность регистрации пользователя с некорректно введёнными данными. В поля имени, фамилии, названии города и названия улицы есть возможность ввести спецсимволы и числа.

**Comment by MaxBQb** [comment]
Хорошо, этого в списке нет, но я зачту как баг
